### ISSUE TITLE
Update node version and upgrade to Environment Files

### ISSUE THREAD

**Issue by oyvindwe** [hkusu/slack-post-action#22]
This is a nice Slack integration as it doesn't rely on a webhook URL as most Slack integration, but it has to be updated to continue to work after 1st June 2023:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: hkusu/slack-post-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
>
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by hkusu** [comment]
merged #23. Thanks !
